name: Build NPM package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and .npmrc
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Read package name
        run: echo "name=$(jq -r -c .name package.json)" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Build snippets
        run: |
          npm run build
          cd dist
          zip ${{ env.name }}.zip *.css

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.name }}-${{ env.version }}.zip
            dist/*
